# Generated by Django 3.2.4 on 2021-06-16 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_remove_menu_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='img',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
