# Generated by Django 3.2.4 on 2021-06-29 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_product'),
        ('orders', '0005_order_product'),
    ]

    operations = [
    ]
